### ISSUE TITLE
[ISSUE] ACCERT Setup for Windows

### ISSUE THREAD

**Issue by DarnellMLambert** [accert-dev/ACCERT#9]
**Describe the issue**
When attempting to set up ACCERT, the ./setup_accert_win.bat command for windows responds with an error that states, "!line:*=!" does not contain any subfolders.

**To Reproduce**
After copying the path of the workbench installation folder, barring no spaces in the folder name, the path is pasted into the workbench.sh file and saved. 

**Expected behavior**
in the file appropriately entitled: "setup_accert_win.bat" all the steps following step 3 should take place, but it ends at this step and a solution could not be found.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Microsoft Edge
 - Version: 11 Home

**Additional context**
After moving a few things around, the code could be used through the terminal, but not through workbench.

-------
For Issue Closure
-------
This review should occur when the issue is going to be closed.
- [x] 1. Is the defect fixed?
- [x] 2. If not fixed, does it contain explanation?
- [x] 3. If closed without a pull request, has an explanation been provided?

**Comment by JiaZhou-PU** [comment]
Tested new install for windows, requires git bash and manually set up workbench path
